In [ ]:
#import Libraries
import pandas as pd
import numpy as np


In [46]:
#read csv
df = pd.read_csv('train_blackFriday.csv')
df


User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
...                    ...                 ...       ...  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[550068 rows x 12 columns]

In [47]:
#number of rows and coulmns
df.shape

(550068, 12)

In [48]:
#show data types found
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [49]:
#show coulmns
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [50]:
#Checking NaN values in the given dataset
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [51]:
#Checking duplicate values in the dataset
df.duplicated().sum()



np.int64(0)

In [52]:
#Renaming the column name to lower case
df.columns  = df.columns.str.lower()

In [53]:
df.columns

Index(['user_id', 'product_id', 'gender', 'age', 'occupation', 'city_category',
       'stay_in_current_city_years', 'marital_status', 'product_category_1',
       'product_category_2', 'product_category_3', 'purchase'],
      dtype='object')

In [54]:
#Removing Reducant Values (user id)
df.drop(['user_id'], axis=1,inplace=True)


In [55]:
#Checking for unique values in each individual column of the dataset
df.nunique()

product_id                     3631
gender                            2
age                               7
occupation                       21
city_category                     3
stay_in_current_city_years        5
marital_status                    2
product_category_1               20
product_category_2               17
product_category_3               15
purchase                      18105
dtype: int64

In [56]:
for column in df.columns:
    print(f"Unique Values in {column}: {df[column].nunique()}")
    

Unique Values in product_id: 3631
Unique Values in gender: 2
Unique Values in age: 7
Unique Values in occupation: 21
Unique Values in city_category: 3
Unique Values in stay_in_current_city_years: 5
Unique Values in marital_status: 2
Unique Values in product_category_1: 20
Unique Values in product_category_2: 17
Unique Values in product_category_3: 15
Unique Values in purchase: 18105


In [57]:
for column in df.columns:
    print(f"Unique Values in {column}: {df[column].unique()}")

Unique Values in product_id: ['P00069042' 'P00248942' 'P00087842' ... 'P00370293' 'P00371644'
 'P00370853']
Unique Values in gender: ['F' 'M']
Unique Values in age: ['0-17' '55+' '26-35' '46-50' '51-55' '36-45' '18-25']
Unique Values in occupation: [10 16 15  7 20  9  1 12 17  0  3  4 11  8 19  2 18  5 14 13  6]
Unique Values in city_category: ['A' 'C' 'B']
Unique Values in stay_in_current_city_years: ['2' '4+' '3' '1' '0']
Unique Values in marital_status: [0 1]
Unique Values in product_category_1: [ 3  1 12  8  5  4  2  6 14 11 13 15  7 16 18 10 17  9 20 19]
Unique Values in product_category_2: [nan  6. 14.  2.  8. 15. 16. 11.  5.  3.  4. 12.  9. 10. 17. 13.  7. 18.]
Unique Values in product_category_3: [nan 14. 17.  5.  4. 16. 15.  8.  9. 13.  6. 12.  3. 18. 11. 10.]
Unique Values in purchase: [ 8370 15200  1422 ...   135   123   613]


In [58]:
#replace each range in age coulmn to its creosspond category ex:0-17 ->child ,18-25 ->teenage, 26-50 -> adult , 51-55+ ->old
df['age'].dtype


dtype('O')

In [59]:

import re 

# Function to categorize the age range
def categorize_age_range(age_range):
    # Regular expression to extract the two numbers from the range
    match = re.match(r"(\d+)-(\d+)|(\d+)\+", str(age_range))
    
    if match:
        if match.group(3):  # For cases like "55+"
            age = int(match.group(3))
            if age >= 55:
                return 'old'
        else:
            start_age = int(match.group(1))
            end_age = int(match.group(2))
            if end_age <= 17:
                return 'child'
            elif end_age <= 25:
                return 'teenage'
            elif end_age <= 50:
                return 'adult'
            else:
                return 'old'
    
    # If the format doesn't match, return NaN
    return np.nan


In [60]:
# Apply the function to the 'age' column
df['age'] = df['age'].apply(categorize_age_range)

# Drop rows with NaN values if there are any
df = df.dropna(subset=['age'])



In [62]:
df[['age']].head(20)

age
0   child
1   child
2   child
3   child
4     old
5   adult
6   adult
7   adult
8   adult
9   adult
10  adult
11  adult
12  adult
13  adult
14    old
15    old
16    old
17    old
18  adult
19  adult

In [63]:
#Checking for unique values for city_years column
df['city_category'].unique()


array(['A', 'C', 'B'], dtype=object)

In [64]:
df.head(20)

product_id gender    age  occupation city_category  \
0   P00069042      F  child          10             A   
1   P00248942      F  child          10             A   
2   P00087842      F  child          10             A   
3   P00085442      F  child          10             A   
4   P00285442      M    old          16             C   
5   P00193542      M  adult          15             A   
6   P00184942      M  adult           7             B   
7   P00346142      M  adult           7             B   
8    P0097242      M  adult           7             B   
9   P00274942      M  adult          20             A   
10  P00251242      M  adult          20             A   
11  P00014542      M  adult          20             A   
12  P00031342      M  adult          20             A   
13  P00145042      M  adult          20             A   
14  P00231342      F    old           9             A   
15  P00190242      F    old           9             A   
16   P0096642      F    old           9             A   
17  P00058442      F    old           9             A   
18  P00036842      M  adult           1             B   
19  P00249542      M  adult          12             C   

   stay_in_current_city_years  marital_status  product_category_1  \
0                           2               0                   3   
1                           2               0                   1   
2                           2               0                  12   
3                           2               0                  12   
4                          4+               0                   8   
5                           3               0                   1   
6                           2               1                   1   
7                           2               1                   1   
8                           2               1                   1   
9                           1               1                   8   
10                          1               1                   5   
11                          1               1                   8   
12                          1               1                   8   
13                          1               1                   1   
14                          1               0                   5   
15                          1               0                   4   
16                          1               0                   2   
17                          1               0                   5   
18                          1               1                   1   
19                         4+               1                   1   

    product_category_2  product_category_3  purchase  
0                  NaN                 NaN      8370  
1                  6.0                14.0     15200  
2                  NaN                 NaN      1422  
3                 14.0                 NaN      1057  
4                  NaN                 NaN      7969  
5                  2.0                 NaN     15227  
6                  8.0                17.0     19215  
7                 15.0                 NaN     15854  
8                 16.0                 NaN     15686  
9                  NaN                 NaN      7871  
10                11.0                 NaN      5254  
11                 NaN                 NaN      3957  
12                 NaN                 NaN      6073  
13                 2.0                 5.0     15665  
14                 8.0                14.0      5378  
15                 5.0                 NaN      2079  
16                 3.0                 4.0     13055  
17                14.0                 NaN      8851  
18                14.0                16.0     11788  
19                 5.0                15.0     19614

In [13]:

#remove + from rows in city_years column

In [65]:

df['stay_in_current_city_years'] = df['stay_in_current_city_years'].str.replace('+', '', regex=False)
df[['stay_in_current_city_years']].head()


stay_in_current_city_years
0                          2
1                          2
2                          2
3                          2
4                          4

In [66]:
#Checking for unique values for category_1 column
df['product_category_1'].unique()


array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9, 20, 19])

In [67]:
#Checking for unique values for category_2 column
df['product_category_2'].unique()

array([nan,  6., 14.,  2.,  8., 15., 16., 11.,  5.,  3.,  4., 12.,  9.,
       10., 17., 13.,  7., 18.])

In [69]:
#fill null you found
df['product_category_2'] = df['product_category_2'].fillna(0)

In [70]:
df['product_category_2'].unique()

array([ 0.,  6., 14.,  2.,  8., 15., 16., 11.,  5.,  3.,  4., 12.,  9.,
       10., 17., 13.,  7., 18.])

In [71]:
#Checking for unique values for category_3 column
df['product_category_3'].unique()

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [72]:
#fill null you found
df['product_category_3'] =df['product_category_3'].fillna(0)

In [73]:
df['product_category_3'].unique()

array([ 0., 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [74]:
#check for null values
df.isnull().sum()

product_id                    0
gender                        0
age                           0
occupation                    0
city_category                 0
stay_in_current_city_years    0
marital_status                0
product_category_1            0
product_category_2            0
product_category_3            0
purchase                      0
dtype: int64

In [75]:
#check for duplicates values
df.duplicated().sum()

np.int64(201)