## Numpy First Task 


In [6]:
import numpy as np
import random

### problem 1 
- Create a 3x3 array that contains a diagonal of nines.


In [5]:
arr = np.zeros((3,3))
np.fill_diagonal(arr , 9)
print (arr)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


### problem 2 
- Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use Boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.


In [28]:

evenNumbers = list(range(2,33,2))
random.shuffle(evenNumbers)

arr = np.array(evenNumbers).reshape(4,4)


Mean = arr.mean()
Std = arr.std()

lower = Mean - 0.5*Std
upper = Mean + 0.5*Std
 # Boolean indexing to pick values within range
values = arr [(arr >= lower)&(arr<= upper)]

print(" Array:\n", arr)
print(f"\n Mean = {Mean:.2f}")
print(f" Standard Deviation = {Std:.2f}")
print(f" Lower Bound = {lower:.2f}")
print(f" Upper Bound = {upper:.2f}\n")
print(f"\nValues within ±0.5 std of mean: {values}\n" )

#  Check each element and print whether it is close to the mean
print("Checking each value:")
for i in range(4):
    for j in range(4):
        value = arr[i][j]
        if lower <= value <= upper:
            print(f"{value :>2}       Close to the mean")
        else:
            print(f"{ value:>2}       Far from the mean")


 Array:
 [[18 22 26 24]
 [ 4 32 28 20]
 [14 10 30  6]
 [16  2 12  8]]

 Mean = 17.00
 Standard Deviation = 9.22
 Lower Bound = 12.39
 Upper Bound = 21.61


Values within ±0.5 std of mean: [18 20 14 16]

Checking each value:
18       Close to the mean
22       Far from the mean
26       Far from the mean
24       Far from the mean
 4       Far from the mean
32       Far from the mean
28       Far from the mean
20       Close to the mean
14       Close to the mean
10       Far from the mean
30       Far from the mean
 6       Far from the mean
16       Close to the mean
 2       Far from the mean
12       Far from the mean
 8       Far from the mean


### problem 3 
- Create a 9x9 array that contains only zero of type int.


In [30]:
arr = np.zeros((9,9) , dtype=int)
print (arr)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


### problem 4
- Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc…



In [ ]:

# create a 2D array of size n * n 
while True:
    try:
        n = int(input("Enter a number for the size of the array: "))
        break  # Exit the loop if input is valid
    except ValueError:
        print("Invalid input! Please enter a valid integer.")

 # first solution 
arr = np.arange(1, n + 1)   # [1, 2, ..., n]
arr = np.tile(arr, (n, 1))  # Repeat it n times vertically

print(" Array 1 " , arr)
print ("#" * 30)

# second solution 
arr = np.zeros((n, n), dtype=int)

for i in range(n):
    arr[:, i] = i + 1  
print("Array 2 " ,  arr)



### problem 5 

- In this problem, we’re given a row of cards where each card has a unique number. There are two players: Sereja and Dima. They take turns choosing cards, and Sereja always starts first.

- On their turn, each player picks the card with the larger number, but they can only choose from the leftmost or rightmost card. After choosing, the number on the card is added to their score.

- The game continues until there are no more cards left. In the end, we want to calculate the total score for each player.

In [ ]:


n = int(input())
arr = np.array(list(map(int , input().split())))

left , right = 0 , n-1
sereja , dima = 0, 0 


Sereja = True

while left <= right:
    if arr[left] > arr[right]:
        chosen = arr[left]
        left += 1
    else:
        chosen = arr[right]
        right -= 1

    if Sereja:
        sereja += chosen
    else:
        dima += chosen

    Sereja = not Sereja

print(sereja, dima) 


### problem 6 
I have  given a photo represented as an `n x m` matrix where each cell contains a character representing the color of a pixel.

The pixel can be one of the following characters:
- `'W'` – White  
- `'G'` – Grey  
- `'B'` – Black  
- `'C'` – Cyan  
- `'M'` – Magenta  
- `'Y'` – Yellow  

- task is to determine whether the photo is **black-and-white** or **colored**.

####  Criteria
- If **all** pixels are from the set `{W, G, B}`, the photo is considered **black-and-white**.
- If **any** pixel is from the set `{C, M, Y}`, then the photo is considered **colored**.




In [ ]:


n, m = map(int, input().split())

pixels = []
for _ in range(n):
    row = input().split()
    pixels.append(row)

arr = np.array(pixels)

colored_pixels = {'C', 'M', 'Y'}

# Check if any pixel in the matrix is one of the colored pixels
if np.isin(arr, list(colored_pixels)).any():
    print("#Color")
else:
    print("#Black&White")
